quotes = [
    {"id": 1, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivation"},
    {"id": 2, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon", "category": "life"},
    {"id": 3, "text": "If you want to lift yourself up, lift up someone else.", "author": "Booker T. Washington", "category": "inspiration"},
    {"id": 4, "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "category": "motivation"},
    {"id": 5, "text": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein", "category": "inspiration"},
    {"id": 6, "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "motivation"},
    {"id": 7, "text": "Happiness depends upon ourselves.", "author": "Aristotle", "category": "life"},
    {"id": 8, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivation"},
    {"id": 9, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivation"},
    {"id": 10, "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt", "category": "motivation"},
    {"id": 11, "text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey", "category": "inspiration"},
    {"id": 12, "text": "Doubt kills more dreams than failure ever will.", "author": "Suzy Kassem", "category": "motivation"},
    {"id": 13, "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "category": "life"},
    {"id": 14, "text": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde", "category": "life"},
    {"id": 15, "text": "Act as if what you do makes a difference. It does.", "author": "William James", "category": "inspiration"},
    {"id": 16, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "creativity"},
    {"id": 17, "text": "Imagination is more important than knowledge.", "author": "Albert Einstein", "category": "creativity"},
    {"id": 18, "text": "Creativity takes courage.", "author": "Henri Matisse", "category": "creativity"},
    {"id": 19, "text": "The purpose of art is washing the dust of daily life off our souls.", "author": "Pablo Picasso", "category": "creativity"},
    {"id": 20, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivation"},
    {"id": 21, "text": "The future belongs to those who prepare for it today.", "author": "Malcolm X", "category": "inspiration"},
    {"id": 22, "text": "Not everything that is faced can be changed, but nothing can be changed until it is faced.", "author": "James Baldwin", "category": "life"},
]